language: ruby
rvm:
  - 2.6.1
branches:
  only: [master, dev]
script:
  - bundle exec rubocop
  - rake
sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler # caching bundler gem packages will speed up build
exclude: [vendor]
install:
- bundle install